//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.17 at 01:27:44 PM CEST 
//


package com.xws.application.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scientificPaperId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="from">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fromId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fromEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="to">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="toId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="toEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "scientificPaperId",
    "from",
    "to",
    "text"
})
@XmlRootElement(name = "notification")
public class Notification {

    @XmlElement(required = true)
    protected String scientificPaperId;
    @XmlElement(required = true)
    protected Notification.From from;
    @XmlElement(required = true)
    protected Notification.To to;
    @XmlElement(required = true)
    protected String text;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;

    /**
     * Gets the value of the scientificPaperId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScientificPaperId() {
        return scientificPaperId;
    }

    /**
     * Sets the value of the scientificPaperId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScientificPaperId(String value) {
        this.scientificPaperId = value;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link Notification.From }
     *     
     */
    public Notification.From getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notification.From }
     *     
     */
    public void setFrom(Notification.From value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link Notification.To }
     *     
     */
    public Notification.To getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notification.To }
     *     
     */
    public void setTo(Notification.To value) {
        this.to = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fromId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fromEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fromId",
        "fromEmail"
    })
    public static class From {

        @XmlElement(required = true)
        protected String fromId;
        @XmlElement(required = true)
        protected String fromEmail;

        /**
         * Gets the value of the fromId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFromId() {
            return fromId;
        }

        /**
         * Sets the value of the fromId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFromId(String value) {
            this.fromId = value;
        }

        /**
         * Gets the value of the fromEmail property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFromEmail() {
            return fromEmail;
        }

        /**
         * Sets the value of the fromEmail property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFromEmail(String value) {
            this.fromEmail = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="toId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="toEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "toId",
        "toEmail"
    })
    public static class To {

        @XmlElement(required = true)
        protected String toId;
        @XmlElement(required = true)
        protected String toEmail;

        /**
         * Gets the value of the toId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getToId() {
            return toId;
        }

        /**
         * Sets the value of the toId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setToId(String value) {
            this.toId = value;
        }

        /**
         * Gets the value of the toEmail property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getToEmail() {
            return toEmail;
        }

        /**
         * Sets the value of the toEmail property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setToEmail(String value) {
            this.toEmail = value;
        }

    }

}
