//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.13 at 04:08:13 PM CEST 
//


package com.xws.application.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xws.application.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Author_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "author");
    private final static QName _Reviewer_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "reviewer");
    private final static QName _TParagraphQuote_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "quote");
    private final static QName _TParagraphRef_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "ref");
    private final static QName _TParagraphFigure_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "figure");
    private final static QName _TParagraphTable_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "table");
    private final static QName _TParagraphList_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "list");
    private final static QName _TParagraphText_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "text");
    private final static QName _TParagraphFormula_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "formula");
    private final static QName _TListDecorator_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "decorator");
    private final static QName _TReferenceArticleLink_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "link");
    private final static QName _TFormulaSubtract_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "subtract");
    private final static QName _TFormulaSubformula_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "subformula");
    private final static QName _TFormulaAdd_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "add");
    private final static QName _TFormulaEqual_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "equal");
    private final static QName _TFormulaVar1_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "var1");
    private final static QName _TFormulaVar2_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "var2");
    private final static QName _TFormulaMultiply_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "multiply");
    private final static QName _TFormulaDivide_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "divide");
    private final static QName _TDecoratorUnderline_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "underline");
    private final static QName _TDecoratorItalic_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "italic");
    private final static QName _TDecoratorBold_QNAME = new QName("https://github.com/nikolina97/xws-tim16-siit-2019", "bold");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xws.application.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BusinessProcess }
     * 
     */
    public BusinessProcess createBusinessProcess() {
        return new BusinessProcess();
    }

    /**
     * Create an instance of {@link Review }
     * 
     */
    public Review createReview() {
        return new Review();
    }

    /**
     * Create an instance of {@link ScientificPaper }
     * 
     */
    public ScientificPaper createScientificPaper() {
        return new ScientificPaper();
    }

    /**
     * Create an instance of {@link TReference }
     * 
     */
    public TReference createTReference() {
        return new TReference();
    }

    /**
     * Create an instance of {@link TReference.Article }
     * 
     */
    public TReference.Article createTReferenceArticle() {
        return new TReference.Article();
    }

    /**
     * Create an instance of {@link TParagraph }
     * 
     */
    public TParagraph createTParagraph() {
        return new TParagraph();
    }

    /**
     * Create an instance of {@link ScientificPaper.References }
     * 
     */
    public ScientificPaper.References createScientificPaperReferences() {
        return new ScientificPaper.References();
    }

    /**
     * Create an instance of {@link ScientificPaper.Abstract }
     * 
     */
    public ScientificPaper.Abstract createScientificPaperAbstract() {
        return new ScientificPaper.Abstract();
    }

    /**
     * Create an instance of {@link TPerson }
     * 
     */
    public TPerson createTPerson() {
        return new TPerson();
    }

    /**
     * Create an instance of {@link BusinessProcess.ReviewAssignments }
     * 
     */
    public BusinessProcess.ReviewAssignments createBusinessProcessReviewAssignments() {
        return new BusinessProcess.ReviewAssignments();
    }

    /**
     * Create an instance of {@link Review.Reviewers }
     * 
     */
    public Review.Reviewers createReviewReviewers() {
        return new Review.Reviewers();
    }

    /**
     * Create an instance of {@link Review.Authors }
     * 
     */
    public Review.Authors createReviewAuthors() {
        return new Review.Authors();
    }

    /**
     * Create an instance of {@link Review.Questions }
     * 
     */
    public Review.Questions createReviewQuestions() {
        return new Review.Questions();
    }

    /**
     * Create an instance of {@link Review.Comments }
     * 
     */
    public Review.Comments createReviewComments() {
        return new Review.Comments();
    }

    /**
     * Create an instance of {@link Review.Grades }
     * 
     */
    public Review.Grades createReviewGrades() {
        return new Review.Grades();
    }

    /**
     * Create an instance of {@link ScientificPaper.Title }
     * 
     */
    public ScientificPaper.Title createScientificPaperTitle() {
        return new ScientificPaper.Title();
    }

    /**
     * Create an instance of {@link ScientificPaper.Authors }
     * 
     */
    public ScientificPaper.Authors createScientificPaperAuthors() {
        return new ScientificPaper.Authors();
    }

    /**
     * Create an instance of {@link ScientificPaper.Chapters }
     * 
     */
    public ScientificPaper.Chapters createScientificPaperChapters() {
        return new ScientificPaper.Chapters();
    }

    /**
     * Create an instance of {@link ScientificPaper.Comments }
     * 
     */
    public ScientificPaper.Comments createScientificPaperComments() {
        return new ScientificPaper.Comments();
    }

    /**
     * Create an instance of {@link TDecorator }
     * 
     */
    public TDecorator createTDecorator() {
        return new TDecorator();
    }

    /**
     * Create an instance of {@link TFormula }
     * 
     */
    public TFormula createTFormula() {
        return new TFormula();
    }

    /**
     * Create an instance of {@link TImage }
     * 
     */
    public TImage createTImage() {
        return new TImage();
    }

    /**
     * Create an instance of {@link TQuestion }
     * 
     */
    public TQuestion createTQuestion() {
        return new TQuestion();
    }

    /**
     * Create an instance of {@link TTableRow }
     * 
     */
    public TTableRow createTTableRow() {
        return new TTableRow();
    }

    /**
     * Create an instance of {@link TList }
     * 
     */
    public TList createTList() {
        return new TList();
    }

    /**
     * Create an instance of {@link TReviewAssignment }
     * 
     */
    public TReviewAssignment createTReviewAssignment() {
        return new TReviewAssignment();
    }

    /**
     * Create an instance of {@link TChapter }
     * 
     */
    public TChapter createTChapter() {
        return new TChapter();
    }

    /**
     * Create an instance of {@link TTable }
     * 
     */
    public TTable createTTable() {
        return new TTable();
    }

    /**
     * Create an instance of {@link TReference.Article.Link }
     * 
     */
    public TReference.Article.Link createTReferenceArticleLink() {
        return new TReference.Article.Link();
    }

    /**
     * Create an instance of {@link TParagraph.Ref }
     * 
     */
    public TParagraph.Ref createTParagraphRef() {
        return new TParagraph.Ref();
    }

    /**
     * Create an instance of {@link TParagraph.Quote }
     * 
     */
    public TParagraph.Quote createTParagraphQuote() {
        return new TParagraph.Quote();
    }

    /**
     * Create an instance of {@link TParagraph.Formula }
     * 
     */
    public TParagraph.Formula createTParagraphFormula() {
        return new TParagraph.Formula();
    }

    /**
     * Create an instance of {@link ScientificPaper.References.Reference }
     * 
     */
    public ScientificPaper.References.Reference createScientificPaperReferencesReference() {
        return new ScientificPaper.References.Reference();
    }

    /**
     * Create an instance of {@link ScientificPaper.Abstract.Keywords }
     * 
     */
    public ScientificPaper.Abstract.Keywords createScientificPaperAbstractKeywords() {
        return new ScientificPaper.Abstract.Keywords();
    }

    /**
     * Create an instance of {@link TPerson.University }
     * 
     */
    public TPerson.University createTPersonUniversity() {
        return new TPerson.University();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPerson }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "author")
    public JAXBElement<TPerson> createAuthor(TPerson value) {
        return new JAXBElement<TPerson>(_Author_QNAME, TPerson.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPerson }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "reviewer")
    public JAXBElement<TPerson> createReviewer(TPerson value) {
        return new JAXBElement<TPerson>(_Reviewer_QNAME, TPerson.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TParagraph.Quote }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "quote", scope = TParagraph.class)
    public JAXBElement<TParagraph.Quote> createTParagraphQuote(TParagraph.Quote value) {
        return new JAXBElement<TParagraph.Quote>(_TParagraphQuote_QNAME, TParagraph.Quote.class, TParagraph.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TParagraph.Ref }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "ref", scope = TParagraph.class)
    public JAXBElement<TParagraph.Ref> createTParagraphRef(TParagraph.Ref value) {
        return new JAXBElement<TParagraph.Ref>(_TParagraphRef_QNAME, TParagraph.Ref.class, TParagraph.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TImage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "figure", scope = TParagraph.class)
    public JAXBElement<TImage> createTParagraphFigure(TImage value) {
        return new JAXBElement<TImage>(_TParagraphFigure_QNAME, TImage.class, TParagraph.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTable }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "table", scope = TParagraph.class)
    public JAXBElement<TTable> createTParagraphTable(TTable value) {
        return new JAXBElement<TTable>(_TParagraphTable_QNAME, TTable.class, TParagraph.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "list", scope = TParagraph.class)
    public JAXBElement<TList> createTParagraphList(TList value) {
        return new JAXBElement<TList>(_TParagraphList_QNAME, TList.class, TParagraph.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDecorator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "text", scope = TParagraph.class)
    public JAXBElement<TDecorator> createTParagraphText(TDecorator value) {
        return new JAXBElement<TDecorator>(_TParagraphText_QNAME, TDecorator.class, TParagraph.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TParagraph.Formula }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "formula", scope = TParagraph.class)
    public JAXBElement<TParagraph.Formula> createTParagraphFormula(TParagraph.Formula value) {
        return new JAXBElement<TParagraph.Formula>(_TParagraphFormula_QNAME, TParagraph.Formula.class, TParagraph.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDecorator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "decorator", scope = TList.class)
    public JAXBElement<TDecorator> createTListDecorator(TDecorator value) {
        return new JAXBElement<TDecorator>(_TListDecorator_QNAME, TDecorator.class, TList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TReference.Article.Link }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "link", scope = TReference.Article.class)
    public JAXBElement<TReference.Article.Link> createTReferenceArticleLink(TReference.Article.Link value) {
        return new JAXBElement<TReference.Article.Link>(_TReferenceArticleLink_QNAME, TReference.Article.Link.class, TReference.Article.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "subtract", scope = TFormula.class)
    public JAXBElement<String> createTFormulaSubtract(String value) {
        return new JAXBElement<String>(_TFormulaSubtract_QNAME, String.class, TFormula.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFormula }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "subformula", scope = TFormula.class)
    public JAXBElement<TFormula> createTFormulaSubformula(TFormula value) {
        return new JAXBElement<TFormula>(_TFormulaSubformula_QNAME, TFormula.class, TFormula.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "add", scope = TFormula.class)
    public JAXBElement<String> createTFormulaAdd(String value) {
        return new JAXBElement<String>(_TFormulaAdd_QNAME, String.class, TFormula.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "equal", scope = TFormula.class)
    public JAXBElement<String> createTFormulaEqual(String value) {
        return new JAXBElement<String>(_TFormulaEqual_QNAME, String.class, TFormula.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "var1", scope = TFormula.class)
    public JAXBElement<String> createTFormulaVar1(String value) {
        return new JAXBElement<String>(_TFormulaVar1_QNAME, String.class, TFormula.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "var2", scope = TFormula.class)
    public JAXBElement<String> createTFormulaVar2(String value) {
        return new JAXBElement<String>(_TFormulaVar2_QNAME, String.class, TFormula.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "multiply", scope = TFormula.class)
    public JAXBElement<String> createTFormulaMultiply(String value) {
        return new JAXBElement<String>(_TFormulaMultiply_QNAME, String.class, TFormula.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "divide", scope = TFormula.class)
    public JAXBElement<String> createTFormulaDivide(String value) {
        return new JAXBElement<String>(_TFormulaDivide_QNAME, String.class, TFormula.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDecorator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "underline", scope = TDecorator.class)
    public JAXBElement<TDecorator> createTDecoratorUnderline(TDecorator value) {
        return new JAXBElement<TDecorator>(_TDecoratorUnderline_QNAME, TDecorator.class, TDecorator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDecorator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "italic", scope = TDecorator.class)
    public JAXBElement<TDecorator> createTDecoratorItalic(TDecorator value) {
        return new JAXBElement<TDecorator>(_TDecoratorItalic_QNAME, TDecorator.class, TDecorator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDecorator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", name = "bold", scope = TDecorator.class)
    public JAXBElement<TDecorator> createTDecoratorBold(TDecorator value) {
        return new JAXBElement<TDecorator>(_TDecoratorBold_QNAME, TDecorator.class, TDecorator.class, value);
    }

}
