//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.18 at 03:35:55 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://github.com/nikolina97/xws-tim16-siit-2019", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.xws.application.model;
