//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.17 at 01:27:44 PM CEST 
//


package com.xws.application.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;anyAttribute processContents='skip' namespace=''/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{https://github.com/nikolina97/xws-tim16-siit-2019}reviewer"/>
 *         &lt;element name="questions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="question" type="{https://github.com/nikolina97/xws-tim16-siit-2019}TQuestion" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="comments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="comment" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{https://github.com/nikolina97/xws-tim16-siit-2019}TParagraph">
 *                           &lt;attribute name="elementId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="grades">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="introduction" type="{https://github.com/nikolina97/xws-tim16-siit-2019}TGrade"/>
 *                   &lt;element name="consclusion" type="{https://github.com/nikolina97/xws-tim16-siit-2019}TGrade"/>
 *                   &lt;element name="experimentResults" type="{https://github.com/nikolina97/xws-tim16-siit-2019}TGrade"/>
 *                   &lt;element name="finalGrade" type="{https://github.com/nikolina97/xws-tim16-siit-2019}TGrade"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="paper_version" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "title",
    "reviewer",
    "questions",
    "comments",
    "grades",
    "paperVersion",
    "date"
})
@XmlRootElement(name = "review")
public class Review {

    @XmlElement(required = true)
    protected Review.Title title;
    @XmlElement(required = true)
    protected TPerson reviewer;
    @XmlElement(required = true)
    protected Review.Questions questions;
    @XmlElement(required = true)
    protected Review.Comments comments;
    @XmlElement(required = true)
    protected Review.Grades grades;
    @XmlElement(name = "paper_version", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger paperVersion;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link Review.Title }
     *     
     */
    public Review.Title getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link Review.Title }
     *     
     */
    public void setTitle(Review.Title value) {
        this.title = value;
    }

    /**
     * Gets the value of the reviewer property.
     * 
     * @return
     *     possible object is
     *     {@link TPerson }
     *     
     */
    public TPerson getReviewer() {
        return reviewer;
    }

    /**
     * Sets the value of the reviewer property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPerson }
     *     
     */
    public void setReviewer(TPerson value) {
        this.reviewer = value;
    }

    /**
     * Gets the value of the questions property.
     * 
     * @return
     *     possible object is
     *     {@link Review.Questions }
     *     
     */
    public Review.Questions getQuestions() {
        return questions;
    }

    /**
     * Sets the value of the questions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Review.Questions }
     *     
     */
    public void setQuestions(Review.Questions value) {
        this.questions = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link Review.Comments }
     *     
     */
    public Review.Comments getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Review.Comments }
     *     
     */
    public void setComments(Review.Comments value) {
        this.comments = value;
    }

    /**
     * Gets the value of the grades property.
     * 
     * @return
     *     possible object is
     *     {@link Review.Grades }
     *     
     */
    public Review.Grades getGrades() {
        return grades;
    }

    /**
     * Sets the value of the grades property.
     * 
     * @param value
     *     allowed object is
     *     {@link Review.Grades }
     *     
     */
    public void setGrades(Review.Grades value) {
        this.grades = value;
    }

    /**
     * Gets the value of the paperVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPaperVersion() {
        return paperVersion;
    }

    /**
     * Sets the value of the paperVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPaperVersion(BigInteger value) {
        this.paperVersion = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="comment" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{https://github.com/nikolina97/xws-tim16-siit-2019}TParagraph">
     *                 &lt;attribute name="elementId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "comment"
    })
    public static class Comments {

        @XmlElement(required = true)
        protected List<Review.Comments.Comment> comment;

        /**
         * Gets the value of the comment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the comment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Review.Comments.Comment }
         * 
         * 
         */
        public List<Review.Comments.Comment> getComment() {
            if (comment == null) {
                comment = new ArrayList<Review.Comments.Comment>();
            }
            return this.comment;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{https://github.com/nikolina97/xws-tim16-siit-2019}TParagraph">
         *       &lt;attribute name="elementId" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Comment
            extends TParagraph
        {

            @XmlAttribute(name = "elementId")
            protected String elementId;

            /**
             * Gets the value of the elementId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getElementId() {
                return elementId;
            }

            /**
             * Sets the value of the elementId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setElementId(String value) {
                this.elementId = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="introduction" type="{https://github.com/nikolina97/xws-tim16-siit-2019}TGrade"/>
     *         &lt;element name="consclusion" type="{https://github.com/nikolina97/xws-tim16-siit-2019}TGrade"/>
     *         &lt;element name="experimentResults" type="{https://github.com/nikolina97/xws-tim16-siit-2019}TGrade"/>
     *         &lt;element name="finalGrade" type="{https://github.com/nikolina97/xws-tim16-siit-2019}TGrade"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "introduction",
        "consclusion",
        "experimentResults",
        "finalGrade"
    })
    public static class Grades {

        protected int introduction;
        protected int consclusion;
        protected int experimentResults;
        protected int finalGrade;

        /**
         * Gets the value of the introduction property.
         * 
         */
        public int getIntroduction() {
            return introduction;
        }

        /**
         * Sets the value of the introduction property.
         * 
         */
        public void setIntroduction(int value) {
            this.introduction = value;
        }

        /**
         * Gets the value of the consclusion property.
         * 
         */
        public int getConsclusion() {
            return consclusion;
        }

        /**
         * Sets the value of the consclusion property.
         * 
         */
        public void setConsclusion(int value) {
            this.consclusion = value;
        }

        /**
         * Gets the value of the experimentResults property.
         * 
         */
        public int getExperimentResults() {
            return experimentResults;
        }

        /**
         * Sets the value of the experimentResults property.
         * 
         */
        public void setExperimentResults(int value) {
            this.experimentResults = value;
        }

        /**
         * Gets the value of the finalGrade property.
         * 
         */
        public int getFinalGrade() {
            return finalGrade;
        }

        /**
         * Sets the value of the finalGrade property.
         * 
         */
        public void setFinalGrade(int value) {
            this.finalGrade = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="question" type="{https://github.com/nikolina97/xws-tim16-siit-2019}TQuestion" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "question"
    })
    public static class Questions {

        @XmlElement(required = true)
        protected List<TQuestion> question;

        /**
         * Gets the value of the question property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the question property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getQuestion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TQuestion }
         * 
         * 
         */
        public List<TQuestion> getQuestion() {
            if (question == null) {
                question = new ArrayList<TQuestion>();
            }
            return this.question;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;anyAttribute processContents='skip' namespace=''/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Title {

        @XmlValue
        protected String value;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }

}
